import { access, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const demoRoot = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(demoRoot, '..', '..');
const evidenceRoot = path.join(demoRoot, '.evidrift');
const marker = path.join(evidenceRoot, '.react-19-demo-generated');
const cli = path.join(repositoryRoot, 'dist', 'src', 'cli.js');

function run(command, args, expectedExitCode = 0) {
  const result = spawnSync(command, args, {
    cwd: demoRoot,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  process.stdout.write(result.stdout ?? '');
  process.stderr.write(result.stderr ?? '');
  if (result.error) throw result.error;
  if (result.status !== expectedExitCode) {
    throw new Error(
      `${path.basename(command)} exited ${String(result.status)}; expected ${expectedExitCode}.`,
    );
  }
}

function runNpm(args) {
  const npmCli = process.env.npm_execpath;
  if (npmCli) {
    run(process.execPath, [npmCli, ...args]);
    return;
  }
  run(process.platform === 'win32' ? 'npm.cmd' : 'npm', args);
}

async function resetEvidence() {
  try {
    await access(evidenceRoot);
  } catch {
    return;
  }
  try {
    await access(marker);
  } catch {
    throw new Error(
      'Refusing to replace an unmarked examples/react-19-useref/.evidrift directory.',
    );
  }
  await rm(evidenceRoot, { recursive: true });
}

async function installedReactTypesVersion() {
  const packageJson = JSON.parse(
    await readFile(path.join(demoRoot, 'node_modules', '@types', 'react', 'package.json'), 'utf8'),
  );
  return packageJson.version;
}

function installReactTypes(version) {
  runNpm([
    'install',
    '--ignore-scripts',
    '--no-audit',
    '--no-fund',
    '--no-package-lock',
    '--no-save',
    `@types/react@${version}`,
  ]);
}

await resetEvidence();

console.log('\n1. Install the exact React 18 type contract (@types/react 18.3.12)');
installReactTypes('18.3.12');
console.log(`   installed: ${await installedReactTypesVersion()}`);

run(process.execPath, [cli, 'init', '--root', demoRoot]);
await writeFile(marker, 'Generated by npm run demo:react-19\n');
run(process.execPath, [
  cli,
  'record',
  '--root',
  demoRoot,
  '--project',
  '.',
  '--package',
  '@types/react',
  '--symbol',
  'useRef',
  '--overload',
  '3',
  '--claim',
  'React useRef permits an omitted initial value.',
  '--code',
  'src/ref.ts:3',
]);
run(process.execPath, [cli, 'check', '--root', demoRoot]);

console.log('\n2. Upgrade only the type contract (@types/react 19.0.1)');
installReactTypes('19.0.1');
console.log(`   installed: ${await installedReactTypesVersion()}`);

console.log('\n3. Evidrift must report the documented React 19 contract drift');
run(process.execPath, [cli, 'check', '--root', demoRoot], 1);

console.log('\nReact 19 drift reproduced successfully.');
